<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /* 콜백 지옥 같은 코드가 형성되지 않게 하는 방법으로 ES6에서 promise가 도입되었다. */

        function increase(number) {

            /* promise에서 resolve는 성공, reject는 실패를 의미한다. */
            const promise = new Promise((resolve, reject) => {
                setTimeout(
                    () => {
                        const result = number + 10;

                        if(result > 50) {
                            const e = new Error('NumberTooBig');

                            /* 실패 시 결과 값을 reject로 전달 */
                            return reject(e);
                        }
                        
                        /* 성공 시 결과 값을 resolve의 인자로 전달 */
                        resolve(result);
                    }, 
                    1000
                );
            });

            return promise;
        }

        /* promise에서 resolve 함수로 전달한 값은 then으로 전달하는 콜백함수의 매개변수를 이용해서 받아 올 수 있다. 
        여러 작업이 연달아 일어난다고 해서 콜백 지옥이 생기는 것이 아니라 then으로 그 다음 작업을 설정하기 때문에 
        가독성이 훨씬 향상된다. */
        increase(0)
            .then(number => {
                console.log(number);

                return increase(number);    // 처리 후 다시 promise를 리턴한다
            })
            .then(number => {
                console.log(number);

                return increase(number);    // 처리 후 다시 promise를 리턴한다
            })
            .then(number => {
                console.log(number);

                return increase(number);    // 처리 후 다시 promise를 리턴한다
            })
            .then(number => {
                console.log(number);

                return increase(number);    // 처리 후 다시 promise를 리턴한다
            })
            .then(number => {
                console.log(number);

                return increase(number);    // 처리 후 다시 promise를 리턴한다
            })
            .then(number => {
                console.log(number);

                return increase(number);    // 처리 후 다시 promise를 리턴한다
            })
            .catch(e => {                   // 에러가 발생하는 것을 catch에서 잡는다
                console.log(e);
            })

    </script>
</body>
</html>